spring:
  profiles:
    active: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    enabled: true