spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;
    username: sa
    password:
    driver-class-name: org.h2.Driver