spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth-manager?requireSSL=true&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: auth-manager
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 9090

logging:
  level:
    org.springframework.security: TRACE
