spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-manager
    driverClassName: com.mysql.cj.jdbc.Driver
    username: auth-manager
    password: 091320f82ca9b5306548d221e7be52aaa8259fb4840458f2379e2b742518adea
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    enabled: true

logging:
  level:
    org.springframework.security: DEBUG