spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth-manager
    driverClassName: com.mysql.cj.jdbc.Driver
    username: auth-manager
    password: 091320f82ca9b5306548d221e7be52aaa8259fb4840458f2379e2b742518adea
