version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    steps:
      - checkout
      - run: mvn clean compile
      - run: mvn install jacoco:report
      - store_artifacts:
          path: target/auth-server-*.jar
