version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster
    steps:
      - checkout
      - run: mvn clean compile
      - run: mvn install jacoco:report
      - store_artifacts:
          path: target/auth-server-*.jar
      - run:
          name: Analyze on Codecov
          command: curl -s https://codecov.io/bash | bash -s
      - run:
          name: Analyze on Codacy
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh)
